[package]
name = "linguist"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
toml = "0.8"
git2 = "0.20"
regex = "1"
serde_json = "1"
tempfile = "3"

[lints.clippy]
pedantic = "warn"
unwrap_used = "warn"
